### ISSUE TITLE
Error "The system cannot find the file specified" when trying to convert filenames with commas

### ISSUE THREAD

**Issue by tabascoterrier** [ConvertAPI/convertapi-cli-go#4]
e.g. trying to convert the file `foo, bar.txt` with `--params="file:@foo, bar.txt, ConvertAttachments:true"`

Results in the error

`convertapi: Conversion parameters are invalid. CreateFile foo: The system cannot find the file specified.`

Presumably as the `--params` values are comma separated, the utility is splitting the filename on the comma.  There doesn't appear to be any way to escape the comma or file parameter.

Seen on Windows 10

```
> .\convertapi.exe --version
convertapi 1
```

**Comment by JonasJasas** [comment]
Now comma inside the parameter value can be escaped with the `\,`
